// <auto-generated />
using System;
using Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426081140_DeploymentPipelineReleaseFlow")]
    partial class DeploymentPipelineReleaseFlow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Domain.Entities.App", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveReleasePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BuildCommand")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeploymentKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("HealthCheckPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectRootPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PublishDirectory")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StartCommand")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("apps", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BuildCommand = "docker build -t hosting-paas-demo .",
                            CreatedAtUtc = new DateTime(2026, 4, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeploymentKind = "BackendApi",
                            Description = "Seed app used to validate the initial schema.",
                            HealthCheckPath = "/health",
                            Name = "Hosting PaaS Demo",
                            Port = 8080,
                            ProjectRootPath = "/src",
                            PublishDirectory = "/src",
                            Slug = "hosting-paas-demo",
                            StartCommand = "docker run -p 8080:8080 hosting-paas-demo",
                            Status = "Draft",
                            UpdatedAtUtc = new DateTime(2026, 4, 24, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArtifactReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeploymentKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReleasePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("WorkspacePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CommitSha");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("AppId", "CreatedAtUtc");

                    b.ToTable("deployments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            ActivatedAtUtc = new DateTime(2026, 4, 24, 0, 2, 0, 0, DateTimeKind.Utc),
                            AppId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ArtifactReference = "seed/demo:v1",
                            Branch = "main",
                            CommitSha = "abcdef1",
                            CreatedAtUtc = new DateTime(2026, 4, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeploymentKind = "BackendApi",
                            FinishedAtUtc = new DateTime(2026, 4, 24, 0, 3, 0, 0, DateTimeKind.Utc),
                            ReleasePath = "/releases/hosting-paas-demo/55555555555555555555555555555555",
                            RepositoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            StartedAtUtc = new DateTime(2026, 4, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Succeeded",
                            Trigger = "Manual",
                            WorkspacePath = "/workspace/hosting-paas-demo/55555555555555555555555555555555"
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.Domain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Hostname")
                        .IsUnique();

                    b.HasIndex("AppId", "IsPrimary")
                        .HasFilter("\"IsPrimary\" = true");

                    b.ToTable("domains", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AppId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAtUtc = new DateTime(2026, 4, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hostname = "demo.hosting-paas.local",
                            IsPrimary = true,
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.EnvironmentVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "Key")
                        .IsUnique();

                    b.ToTable("environment_variables", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            AppId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAtUtc = new DateTime(2026, 4, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSecret = false,
                            Key = "ASPNETCORE_ENVIRONMENT",
                            UpdatedAtUtc = new DateTime(2026, 4, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "Production"
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeploymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "TimestampUtc");

                    b.HasIndex("DeploymentId", "TimestampUtc");

                    b.ToTable("log_entries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            AppId = new Guid("11111111-1111-1111-1111-111111111111"),
                            DeploymentId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Level = "Information",
                            Message = "Initial demo deployment seeded for local development.",
                            Source = "seed",
                            TimestampUtc = new DateTime(2026, 4, 24, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uuid");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CloneUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("ConnectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalRepositoryId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("WebhookSecret")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .IsUnique();

                    b.HasIndex("Provider", "Owner", "Name", "Branch");

                    b.ToTable("repositories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AppId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Branch = "main",
                            CloneUrl = "https://github.com/example/hosting-paas-demo.git",
                            ConnectedAtUtc = new DateTime(2026, 4, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExternalRepositoryId = "repo_seed_demo",
                            Name = "hosting-paas-demo",
                            Owner = "example",
                            Provider = "GitHub",
                            WebhookSecret = "change-me"
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.Deployment", b =>
                {
                    b.HasOne("Api.Domain.Entities.App", "App")
                        .WithMany("Deployments")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entities.Repository", "Repository")
                        .WithMany("Deployments")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("App");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Api.Domain.Entities.Domain", b =>
                {
                    b.HasOne("Api.Domain.Entities.App", "App")
                        .WithMany("Domains")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("Api.Domain.Entities.EnvironmentVariable", b =>
                {
                    b.HasOne("Api.Domain.Entities.App", "App")
                        .WithMany("EnvironmentVariables")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("Api.Domain.Entities.LogEntry", b =>
                {
                    b.HasOne("Api.Domain.Entities.App", "App")
                        .WithMany("LogEntries")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entities.Deployment", "Deployment")
                        .WithMany("LogEntries")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("App");

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("Api.Domain.Entities.Repository", b =>
                {
                    b.HasOne("Api.Domain.Entities.App", "App")
                        .WithOne("Repository")
                        .HasForeignKey("Api.Domain.Entities.Repository", "AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("Api.Domain.Entities.App", b =>
                {
                    b.Navigation("Deployments");

                    b.Navigation("Domains");

                    b.Navigation("EnvironmentVariables");

                    b.Navigation("LogEntries");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Api.Domain.Entities.Deployment", b =>
                {
                    b.Navigation("LogEntries");
                });

            modelBuilder.Entity("Api.Domain.Entities.Repository", b =>
                {
                    b.Navigation("Deployments");
                });
#pragma warning restore 612, 618
        }
    }
}
